/**
 * RailSim2 keyword definitions — Single Source of Truth.
 *
 * Extracted from syntaxes/railsim2.tmLanguage.json.
 * The parser does NOT depend on this; only the validator uses it.
 */

// ---------------------------------------------------------------------------
// Object names (storage.type) — from sym-objects capture group 2
// ---------------------------------------------------------------------------

export const OBJECT_NAMES = [
  "Axle",
  "Background",
  "Base",
  "Body",
  "ChangeMaterial",
  "Circle",
  "CrankZY",
  "DefineAnimation",
  "DefineSwitch",
  "DynamicRotation",
  "EditCtrl",
  "EnvInfo",
  "Face",
  "Frame",
  "FrontCabin",
  "GirderInfo",
  "Head",
  "Headlight",
  "Hexagon",
  "Interface",
  "Interval",
  "Joint",
  "Joint3D",
  "JointZY",
  "JointZYX",
  "Landscape",
  "LensFlare",
  "Lighting",
  "Line",
  "LineInfo",
  "Link",
  "ListView",
  "Material",
  "Model",
  "Moon",
  "NormalCursor",
  "Object3D",
  "ObjectZY",
  "Particle",
  "PierInfo",
  "PistonZY",
  "Platform",
  "PluginHeader",
  "PluginTree",
  "PoleInfo",
  "PopupMenu",
  "PrimaryAssembly",
  "Profile",
  "RailInfo",
  "ResizeCursor1",
  "ResizeCursor2",
  "ResizeCursor3",
  "ResizeCursor4",
  "Set",
  "Slide",
  "Sound",
  "SoundEffect",
  "SoundInfo",
  "StaticMove",
  "StaticRotation",
  "StationInfo",
  "StructInfo",
  "Sun",
  "SurfaceInfo",
  "TailCabin",
  "Texture",
  "TieInfo",
  "Tilt",
  "TrackWind",
  "TrainInfo",
  "TriangleZY",
  "Vertex",
  "Whiteout",
  "Windmill",
  "Wireframe",
] as const satisfies readonly string[];

// ---------------------------------------------------------------------------
// Control keywords (keyword.control) — from sym-objects capture group 3
// ---------------------------------------------------------------------------

export const CONTROL_KEYWORDS = [
  "ApplySwitch",
  "Else",
  "If",
] as const satisfies readonly string[];

// ---------------------------------------------------------------------------
// Case keywords (keyword.control.switch) — from sym-case-clause
// ---------------------------------------------------------------------------

export const CASE_KEYWORDS = [
  "Case",
  "Default",
] as const satisfies readonly string[];

// ---------------------------------------------------------------------------
// Property names (variable.parameter.property) — from sym-properties
// ---------------------------------------------------------------------------

export const PROPERTY_NAMES = [
  "Acceleration",
  "AccelerationRel",
  "AirResistance",
  "AlphaZeroTest",
  "Ambient",
  "AnalogClock",
  "AnimationTime",
  "ArrowModelFileName",
  "ArrowModelScale",
  "AttachCoord",
  "AttachDir",
  "AttachObject",
  "AttachUp",
  "AttachX",
  "AxialInclination",
  "BackgroundColor",
  "BaseAlt",
  "BaseToPierLocal",
  "BlendMode",
  "BranchRail",
  "BuildMinAlt",
  "ButtonFontColor",
  "CantRatio",
  "CastShadow",
  "ChangeAlpha",
  "ChangeModel",
  "ChangeTexture",
  "Color",
  "CompassModelFileName",
  "CompassModelScale",
  "ConnectRail",
  "ConvertClauseColor",
  "ConvertFontColor",
  "Coord",
  "Cursor2DAnimFrame",
  "Cursor2DAnimNumber",
  "Cursor2DHotSpot",
  "Cursor2DSize",
  "Deceleration",
  "DecelerationRel",
  "DefaultBaseColor",
  "DefaultBaseColorEven",
  "DefaultBaseColorOdd",
  "DefaultFontColor",
  "Description",
  "Diameter",
  "Diffuse",
  "DirLink",
  "Direction",
  "Directional",
  "DisabledFontColor",
  "DisabledShadowColor",
  "DisconnectRail",
  "Displacement",
  "Distance",
  "DoorClosingTime",
  "EditBaseColor",
  "EditFontColor",
  "Emissive",
  "EnableCant",
  "Entry",
  "EnvMap",
  "EnvMapTexFileName",
  "ErrorWaveFileName",
  "FinalRadius",
  "FixAxis",
  "FixPosition",
  "FixRight",
  "FlattenCant",
  "FloatFontColor",
  "FocusFrameColor",
  "FontName",
  "Frame",
  "FrameTexFileName",
  "FrontLimit",
  "Gauge",
  "GirderPlugin",
  "Gravity",
  "GroupCommon",
  "HeadToPierLocal",
  "Height",
  "IconRect",
  "IconTexFileName",
  "IconTexture",
  "IgnoreCant",
  "ImageSize",
  "Inclination",
  "InfoFontColor",
  "InitialPhase",
  "InitialRadius",
  "InnerColor",
  "Interval",
  "JointInterval",
  "JointToHeadLocal",
  "LabelFontColor",
  "Latitude",
  "Lifetime",
  "LiftRailSurface",
  "LinePlugin",
  "LinkCoord",
  "LinkModelFileName",
  "LinkModelScale",
  "LocalCoord",
  "Loop",
  "MaterialID",
  "MaxAcceleration",
  "MaxAngle",
  "MaxCant",
  "MaxDeceleration",
  "MaxDeflection",
  "MaxDistance",
  "MaxInterval",
  "MaxQty",
  "MaxVelocity",
  "MinInterval",
  "MinQty",
  "ModelFileName",
  "ModelScale",
  "MouseDownWaveFileName",
  "MouseUpWaveFileName",
  "NightThreshold",
  "NoCastShadow",
  "NoReceiveShadow",
  "NoShadow",
  "Normal",
  "NumberedFrame",
  "Offset",
  "OpenDoor",
  "OuterColor",
  "ParentObject",
  "PierPlugin",
  "PluginAuthor",
  "PluginName",
  "PluginType",
  "PolePlugin",
  "PostAnimationDelay",
  "PostReverseDelay",
  "Power",
  "PreAnimationDelay",
  "PreReverseDelay",
  "Radius",
  "RailPlugin",
  "RailSimVersion",
  "ReverseTime",
  "RevolutionPeriod",
  "RotateTexture",
  "RotationAngle",
  "RotationAxis",
  "RotationSpeed",
  "RotationUVFrame",
  "ScaleTexture",
  "ScreenShotWaveFileName",
  "SegmentModelFileName",
  "SegmentModelScale",
  "SelectedBaseColor",
  "SelectedFontColor",
  "SetAnimation",
  "ShadowColor",
  "ShiftTexture",
  "SizeX",
  "SizeZ",
  "SkyColor",
  "SlideUVFrame",
  "SourceCoord",
  "Specular",
  "StartAngle",
  "StaticFontColor",
  "Stoppable",
  "SunAlt",
  "SurfaceAlt",
  "Symmetric",
  "TailLimit",
  "TaperX",
  "TaperY",
  "TaperZ",
  "TexFileName",
  "TexU",
  "TexVPerMeter",
  "TextureFileName",
  "TiePlugin",
  "TiledUVFrame",
  "TiltRatio",
  "TiltSpeed",
  "TitleBarFontColor",
  "TrackInterval",
  "TrackNum",
  "TrackSpeed",
  "TransformTexture",
  "Transparent",
  "TrolleyAlt",
  "Turbulence",
  "Turn",
  "Twinkle",
  "UpLink",
  "UseTexture",
  "UseWallpaper",
  "VelocityRel",
  "VideoStartWaveFileName",
  "VideoStopWaveFileName",
  "Volume",
  "WaveFileName",
  "WheelSound",
  "WheelSoundFile",
  "WindDirModelFileName",
  "WindDirModelScale",
] as const satisfies readonly string[];

// ---------------------------------------------------------------------------
// Constants (support.constant + yes/no) — from constant match + yes-no
// ---------------------------------------------------------------------------

export const CONSTANTS = [
  "Add",
  "Alpha",
  "DayAlpha",
  "Down",
  "Env",
  "Girder",
  "Hour",
  "Line",
  "Minute",
  "NightAlpha",
  "Pier",
  "Pole",
  "Rail",
  "Second",
  "Skin",
  "Station",
  "Struct",
  "Surface",
  "Tie",
  "Train",
  "Up",
  "no",
  "yes",
] as const satisfies readonly string[];

// ---------------------------------------------------------------------------
// Set versions for O(1) lookup
// ---------------------------------------------------------------------------

export const OBJECT_NAME_SET: ReadonlySet<string> = new Set(OBJECT_NAMES);
export const CONTROL_KEYWORD_SET: ReadonlySet<string> = new Set(CONTROL_KEYWORDS);
export const CASE_KEYWORD_SET: ReadonlySet<string> = new Set(CASE_KEYWORDS);
export const PROPERTY_NAME_SET: ReadonlySet<string> = new Set(PROPERTY_NAMES);
export const CONSTANT_SET: ReadonlySet<string> = new Set(CONSTANTS);

// ---------------------------------------------------------------------------
// Classifier
// ---------------------------------------------------------------------------

export type IdentifierKind =
  | "object"
  | "control"
  | "case"
  | "property"
  | "constant"
  | "unknown";

export function classifyIdentifier(name: string): IdentifierKind {
  if (OBJECT_NAME_SET.has(name)) return "object";
  if (CONTROL_KEYWORD_SET.has(name)) return "control";
  if (CASE_KEYWORD_SET.has(name)) return "case";
  if (PROPERTY_NAME_SET.has(name)) return "property";
  if (CONSTANT_SET.has(name)) return "constant";
  return "unknown";
}
